### ISSUE TITLE
Movelog not properly closed

### ISSUE THREAD

**Issue by ngjunsiang** [PotatoStealer/ChessGame#16]
https://github.com/PotatoStealer/ChessGame/blob/466cd7bfe52abf0ba22ba4ff3e6176f3736e9e6a/chess.py#L19

## Issue

While testing game:

```
/home/runner/ChessGame/chess.py:19: ResourceWarning: unclosed file <_io.TextIOWrapper name='moves.txt' mode='w' encoding='UTF-8'>
  open('moves.txt','w')
```

## Suggested resolution

Close the file handle properly

**Comment by Joseph31416** [comment]
Fixed by closing in line 20.
